### ISSUE TITLE
withBehavior()?

### ISSUE THREAD

**Issue by leoismyfriend** [lmatteis/b-thread#1]
hi, I'm reading your intro on behavioral programming on freecodecamp but I can't find the withBehavior() function in the library.

Can you point this out to me please?

Thanks

**Comment by lmatteis** [comment]
This is just the pure JavaScript implementation. For something that works with React and uses withBehavior please check: https://codesandbox.io/s/mwyow52qp

**Comment by leoismyfriend** [comment]
Thanks. Love the work you're doing in this area.
