### ISSUE TITLE
how can i  use async api in b-thread?

### ISSUE THREAD

**Issue by stormslowly** [lmatteis/b-thread#3]
in your example, all calls in b-threads are sync functions.
but in a real case, I will use  some async functions (eg. HTTP request)
how can I do that?

**Comment by lmatteis** [comment]
Sorry for the late reply @stormslowly 

Essentially you can use promises in the function generators and dynamically create another b-thread that requests an event:

```js

bp.addBThread('foo', ++priority, function *() {
  yield { wait: 'addHot' }
  callSomePromise()
    .then(() => bp.addBThread('bar', ++priority, function *() {
      yield { request: 'promiseResolved' }
    }))
});
// another b-thread can wait for 'promiseResolved'
function *() {
  yield { wait: 'promiseResolved' }
  // do something else
}
```
